ALTER TABLE leads ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE leads ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE leads ADD COLUMN is_restored BOOLEAN DEFAULT FALSE;

ALTER TABLE forms ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE forms ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE forms ADD COLUMN is_restored BOOLEAN DEFAULT FALSE;
